### ISSUE TITLE
Uso de tags html semânticas

### ISSUE THREAD

**Issue by jordyalcides** [RaizaCirne/formulario-cadastro-devs#1]
Utilize tags mais semânticas para ajudar na acessibilidade e SEO da página.

Exemplo de tags: header, main, footer, article, section...

**Comment by RaizaCirne** [comment]
Caro @jordyalcides, atualizei o projeto com uso de tags html semânticas incluindo **header e main**. Você pode [acessar projeto atualizado aqui](https://github.com/RaizaCirne/formulario-cadastro-devs).
